stages:
  - build
  - test
  - deploy_test
  - deploy_production

variables:
  DOCKER_HOST: "ssh://root@104.248.90.5"

# Job for building Django project -
build:
  stage: build
  image: python:3.9
  before_script:
    - apt-get update && apt-get install -y openssh-client
  script:
    - pip install -r base.txt

# Job for tests
test:
  stage: test
  image: python:3.9
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - pip install -r local.txt
  script:
    - python manage.py test

# Job for deploying to Test env in Digital Ocean

#deploy_test:
#  stage: deploy_test
#  image: python:3.9
#  before_script:
#    - apt-get update && apt-get install -y openssh-client
#  script:
#    - ssh root@104.248.90.5 'cd /devops-coding-challenge && git pull origin main && ./manage.py migrate && ./manage.py collectstatic --no-input'

# Job for deploying to Prod env in Digital Ocean
deploy_production:
  stage: deploy_production
  image: python:3.9
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - pip install -r production.txt
  script:
    - ssh root@104.248.90.5 'cd /devops-coding-challenge && git pull origin main && ./manage.py migrate && ./manage.py collectstatic --no-input'
